repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
    exclude: ^(modules/|charts/|dockerfiles/)
  - id: pretty-format-json
    args: ['--autofix']
    exclude: 'Pipfile.lock'
  - id: requirements-txt-fixer
    args: [requirements.txt]
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: no-commit-to-branch
    args: ['--branch', 'master']

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
