{{- with .Values.frontendIngress }}
{{- $hosts := printf "(Host(`%s`))" ( join "`) || Host(`" .hosts ) }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loki-frontend
spec:
  secretName: loki-frontend-tls
  dnsNames:
    {{- toYaml .hosts | nindent 4 }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ .clusterIssuer }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: loki-frontend
spec:
  entryPoints:
  - websecure
  routes:
  - match: {{ printf "(%s)" $hosts | quote }}
    kind: Rule
    services:
    - name: {{ .serviceName }}
      port: 3100
    middlewares:
{{- with .allowedIPs }}
    - name: ip-whitelist
{{- end }}
    - name: basic-auth
  tls:
    secretName: loki-frontend-tls
{{- with .allowedIPs }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ip-whitelist
spec:
  ipWhiteList:
    sourceRange:
    {{- range . }}
      - {{ . | quote }}
    {{- end }}
{{- end }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
spec:
  basicAuth:
    secret: basic-auth-creds
---
apiVersion: v1
data:
  users: {{ .lokiCredentials }}
kind: Secret
metadata:
  name: basic-auth-creds
{{- end }}
