---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    {{- include "devops-stack-module-keycloak.labels" $ | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
