FROM apache/airflow:latest
RUN pip install --upgrade pip
COPY requirements.txt /
RUN pip install -r /requirements.txt
RUN pip install -U ray[all]
RUN pip install -U atom-ml[ray]
RUN pip install -U modin[ray]
