{{- range $key, $value := index $.Values "traefik" "middlewares" "redirections" }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $key }}
spec:
  redirectRegex:
    permanent: {{ $value.permanent }}
    regex: {{ $value.regex }}
    replacement: {{ $value.replacement }}
{{- end }}
