apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - all.yaml

patches:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: .*\.monitoring\.coreos\.com
    patch: |-
      - op: add
        path: "/metadata/annotations"
        value:
          "argocd.argoproj.io/sync-options": "Replace=true"
