apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mlflow.fullname" . }}-env-configmap
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.backendStore.postgres.enabled }}
  PGHOST: {{ required "postgres host must be specified" .Values.backendStore.postgres.host }}
  PGPORT: {{ required "postgres port must be specified" .Values.backendStore.postgres.port | quote }}
  PGDATABASE: {{ required "postgres database must be specified" .Values.backendStore.postgres.database }}
{{- end }}
{{- if .Values.backendStore.mysql.enabled }}
  MYSQL_HOST: {{ required "mysql host must be specified" .Values.backendStore.mysql.host }}
  MYSQL_TCP_PORT: {{ required "mysql port must be specified" .Values.backendStore.mysql.port | quote }}
  MYSQL_DATABASE: {{ required "mysql database must be specified" .Values.backendStore.mysql.database }}
{{- end }}

{{- if and (or .Values.backendStore.postgres.enabled .Values.backendStore.mysql.enabled) .Values.backendStore.databaseMigration }}
{{- $dbConnectionDriver := "" }}
{{- if and .Values.backendStore.postgres.enabled .Values.backendStore.postgres.driver }}
  {{- $dbConnectionDriver = printf "+%s" .Values.backendStore.postgres.driver }}
{{- else if and .Values.backendStore.mysql.enabled .Values.backendStore.mysql.driver }}
  {{- $dbConnectionDriver = printf "+%s" .Values.backendStore.mysql.driver }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mlflow.fullname" . }}-migrations
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  migrations.py: |-
    from mlflow.store.db import utils
    import os


  {{- if .Values.backendStore.postgres.enabled }}
    engine = utils.create_sqlalchemy_engine_with_retry("postgresql{{ $dbConnectionDriver }}://")
  {{- else if .Values.backendStore.mysql.enabled }}
    username = os.getenv("MYSQL_USERNAME")
    password = os.getenv("MYSQL_PWD")
    host = os.getenv("MYSQL_HOST")
    port = os.getenv("MYSQL_TCP_PORT")
    database = os.getenv("MYSQL_DATABASE")
    engine = utils.create_sqlalchemy_engine_with_retry(f"mysql{{ $dbConnectionDriver }}://{username}:{password}@{host}:{port}/{database}")
  {{- end }}
    utils._initialize_tables(engine)
{{- end }}
{{- if and (or .Values.backendStore.postgres.enabled .Values.backendStore.mysql.enabled) .Values.backendStore.databaseConnectionCheck }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mlflow.fullname" . }}-dbchecker
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ (.Files.Glob "files/dbchecker.sh").AsConfig | nindent 2 }}
{{- end }}
