apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  namespace: cicd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: management
  project: default
  source:
    repoURL: 'https://emberstack.github.io/helm-charts'
    targetRevision: 7.0.151        
    chart: reflector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
