{
 "title": "Strimzi Kafka Bridge",
 "tags": [
  "Strimzi",
  "Kafka"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_bridge_http_server_active_connections{container=~\"^.+-bridge\"})"
    }
   ]
  },
  {
   "title": "HTTP requests being processed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_bridge_http_server_active_requests{container=~\"^.+-bridge\"})"
    }
   ]
  },
  {
   "title": "KafkaProducer instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(strimzi_bridge_kafka_producer_count)"
    }
   ]
  },
  {
   "title": "KafkaProducers connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_bridge_kafka_producer_connection_count)"
    }
   ]
  },
  {
   "title": "KafkaConsumer instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_bridge_kafka_consumer_last_heartbeat_seconds_ago != bool -1)"
    }
   ]
  },
  {
   "title": "KafkaConsumers connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_bridge_kafka_consumer_connection_count)"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Producer rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "records/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_kafka_producer_record_send_total{topic != \"\"}[1m])) by (clientId, topic)"
    }
   ]
  },
  {
   "title": "Producer rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_kafka_producer_byte_total{topic != \"\"}[1m])) by (clientId, topic)"
    }
   ]
  },
  {
   "title": "Average producer request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(strimzi_bridge_kafka_producer_request_latency_avg{type = \"producer-metrics\"}) by (clientId)"
    }
   ]
  },
  {
   "title": "Consumer rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_kafka_consumer_bytes_consumed_total{topic != \"\"}[1m])) by (clientId, topic)"
    }
   ]
  },
  {
   "title": "Consumer rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "records/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_kafka_consumer_records_consumed_total{topic != \"\"}[1m])) by (clientId, topic)"
    }
   ]
  },
  {
   "title": "Consumer Assigned Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "partitions" }
   ],
   "targets": [
    {
     "expr": "sum(strimzi_bridge_kafka_consumer_assigned_partitions) by (clientId)"
    }
   ]
  },
  {
   "title": "Average consumer idle poll",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "sec" }
   ],
   "targets": [
    {
     "expr": "sum(strimzi_bridge_kafka_consumer_poll_idle_ratio_avg) by (clientId)"
    }
   ]
  },
  {
   "title": "Consumer commit rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "commits/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_kafka_consumer_commit_total[1m])) by (clientId)"
    }
   ]
  },
  {
   "title": "Consumer commits latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(strimzi_bridge_kafka_consumer_commit_latency_avg) by (clientId)"
    }
   ]
  },
  {
   "title": "Consumer fetch rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(strimzi_bridge_kafka_consumer_fetch_rate) by (clientId)"
    }
   ]
  },
  {
   "title": "Average consumer fetch latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(strimzi_bridge_kafka_consumer_fetch_latency_avg) by (clientId)"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Requests rate by HTTP method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_http_server_requests_total{container=~\"^.+-bridge\"}[1m])) by (method)"
    }
   ]
  },
  {
   "title": "HTTP Requests and Response rate by codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_http_server_requests_total{container=~\"^.+-bridge\"}[1m]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(strimzi_bridge_http_server_requests_total{code=~\"^2..$\", container=~\"^.+-bridge\"}[1m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(rate(strimzi_bridge_http_server_requests_total{code=~\"^4..$\", container=~\"^.+-bridge\"}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(strimzi_bridge_http_server_requests_total{code=~\"^5..$\", container=~\"^.+-bridge\"}[1m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "HTTP send rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_http_server_bytes_written_total{container=~\"^.+-bridge\"}[1m])) by (container)"
    }
   ]
  },
  {
   "title": "HTTP receive rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_http_server_bytes_read_total{container=~\"^.+-bridge\"}[1m])) by (container)"
    }
   ]
  },
  {
   "title": "Send messages rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_http_server_requests_total{container=~\"^.+-bridge\",method=\"POST\",path=~\"/topics/[^/]+\"}[1m])) by (path)"
    }
   ]
  },
  {
   "title": "Send messages To Partition rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_http_server_requests_total{container=~\"^.+-bridge\",method=\"POST\",path=~\"/topics/.+/partitions/[0-9]+\"}[1m])) by (path)"
    }
   ]
  },
  {
   "title": "Consumer instance creation rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_http_server_requests_total{container=~\"^.+-bridge\",method=\"POST\",path=~\"/consumers/[^/]+\"}[1m])) by (path)"
    }
   ]
  },
  {
   "title": "Subscribe to topics rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_http_server_requests_total{container=~\"^.+-bridge\",method=\"POST\",path=~\"/consumers/.+/instances/.+/subscription\"}[1m])) by (path)"
    }
   ]
  },
  {
   "title": "Consumer instance deletion rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_http_server_requests_total{container=~\"^.+-bridge\",method=\"DELETE\",path=~\"/consumers/.+/instances/.+\"}[1m])) by (path)"
    }
   ]
  },
  {
   "title": "Poll for messages rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_http_server_requests_total{container=~\"^.+-bridge\",method=\"GET\",path=~\"/consumers/.+/instances/.+/records\"}[1m])) by (path)"
    }
   ]
  },
  {
   "title": "Commit offsets rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(strimzi_bridge_http_server_requests_total{container=~\"^.+-bridge\",method=\"POST\",path=~\"/consumers/.+/instances/.+/offsets\"}[1m])) by (path)"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{container=~\"^.+-bridge\"})"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{container=~\"^.+-bridge\"}[5m]))"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{container=~\"^.+-bridge\"}[5m]))"
    }
   ]
  }
 ]
}