suite: test service account

templates:
  - serviceaccount.yaml

tests:
  - it: should be empty when service account is not created
    set:
      serviceAccount.create: false
    asserts:
      - hasDocuments:
          count: 0

  - it: should match snapshot of default values
    set:
      serviceAccount.annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::111122223333:role/iam-role-name"
    release:
      name: mlflow
      namespace: mlflow
    chart:
      version: 1.0.0
      appVersion: 1.0.0
    asserts:
      - matchSnapshot: { }
