suite: test service

templates:
  - service.yaml

tests:
  - it: should use different port number when we change it
    set:
      service.port: 80
    asserts:
      - equal:
          path: spec.ports[0].port
          value: 80
      - equal:
          path: spec.ports[0].targetPort
          value: 80

  - it: should use different port name when we change it
    set:
      service.name: differentname
    asserts:
      - equal:
          path: spec.ports[0].name
          value: differentname

  - it: should match snapshot of default values
    set:
      service.annotations:
        test-key: test-value
    release:
      name: mlflow
      namespace: mlflow
    chart:
      version: 1.0.0
      appVersion: 1.0.0
    asserts:
      - matchSnapshot: { }
