apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  namespace: cicd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: deepstorage
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.2.0
    helm:
      values: |-
        auth:
          existingSecret: minio-secrets
        defaultBuckets: "landing, lakehouse"
        service:
          type: LoadBalancer
        persistence:
          size: 10Gi
        volumePermissions:
          enabled: true
    chart: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
