apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: cicd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: deepstorage
  project: default
  source:
    repoURL: 'https://operator.min.io/'
    targetRevision: 4.5.5
    helm:
      values: |-
        operator:
          replicaCount: 2
    chart: operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
