{{- with .Values.azureIdentity }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: prometheus
spec:
  type: 0
  resourceID: {{ .resourceID }}
  clientID: {{ .clientID }}
{{- end }}
