{{- with .Values.azureIdentity }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: prometheus-binding
spec:
  azureIdentity: prometheus
  selector: prometheus
{{- end }}
