# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: MachineLearning
  licenses: Apache-2.0
apiVersion: v2
appVersion: 4.0.1
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 12.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: JupyterHub brings the power of notebooks to groups of users. It gives users access to computational environments and resources without burdening the users with installation and maintenance tasks.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/jupyterhub/img/jupyterhub-stack-220x234.png
keywords:
  - python
  - scientific
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: jupyterhub
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/jupyterhub
version: 4.1.7
