apiVersion: v2
dependencies:
- name: argo-cd
  repository: https://argoproj.github.io/argo-helm
  version: 5.45.3
description: |
  This chart installs and configures:

  * Argo CD official chart
  * A Grafana dashboard for Argo CD
  * An `OAuthClient` Kubernetes object if the OpenShift 4 option is enabled
name: ArgoCD
version: "0"
